In [2]:
import numpy as np

a1 = np.array([[3, 1, -1], [1, 2, -1], [1, 1, 5]])
b1 = np.array([181.05, 108.35, 142.55])


a2 = np.array([[1, -1, 2], [3, 2, 1], [2, -3, -2]])
b2 = np.array([5, 10, -10])


a3 = np.array([[5, 1, 1, 1], [2, -1, -1, 1], [3, -1, 2, -2], [5, -4, 3, -2]])
b3 = np.array([685, 165, 256, 361])


a4 = np.array([[1, 3, 5], [2, 5, 1], [2, 3, 8]])
b4 = np.array([10, 8, 3])

def gauss(a,b): #a - macierz wspolczynnikow, b - wektor wyrazow wolnych
    n = len(b)
    # procedura eliminacji
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k]/float(a[k,k])
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
    # procedura wyliczania rozwiazania i zapisu do macierzy b
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/float(a[k,k])
    return b

print('Rozwiazania np.linalg.solve:')
print(np.linalg.solve(a1,b1))
print(np.linalg.solve(a2,b2))
print(np.linalg.solve(a3,b3))
print(np.linalg.solve(a4,b4))
print('Rozwiazania z metody gaussa:')
rozw1 = gauss(a1,b1)
print(rozw1)
rozw2 = gauss(a2,b2)
print(rozw2)
rozw3 = gauss(a3,b3)
print(rozw3)
rozw4 = gauss(a4,b4)
print(rozw4)

# Wnioski:
# Metoda linealg.solve zwraca dokładne rozwiązanie układu równań liniowych.
# Wartości zwracane przez własnoręcznie napisaną funkcję gauss dla
# układu równań B są dokładne, natomiast dla układów A, C i D 
# znacząco różnią się od tych zwracanych przez funkcję numpy.linalg.solve.

# Działanie funkcji gauss:
# W pierwszej pętli for następuje eliminacja. Dla każdego wiersza a 
# poniżej k-tego wiersza, jeśli a[i,k] != 0, to obliczany jest współczynnik
# lam = a[i,k]/a[k,k], a następnie odejmowana jest od wiersza a[i]
# odpowiednia ilość k-tego wiersza pomnożonego przez lam.
# W drugiej pętli for następuje wyliczenie rozwiązania. Dla każdego wiersza
# a od końca do początku, obliczane jest b[k] = (b[k] - sum(a[k,k+1:n]*b[k+1:n]))/a[k,k].
# W ten sposób otrzymujemy rozwiązanie układu równań liniowych.


Rozwiazania np.linalg.solve:
[53.   33.3  11.25]
[1. 2. 3.]
[106.  52.  49.  54.]
[-9.28  5.16  0.76]
Rozwiazania z metody gaussa:
[49.83 48.   16.44]
[1 2 3]
[96 37 72 95]
[-26  12   0]
